### ISSUE TITLE
При получении списка uid друзей возвращается Unknown api response 

### ISSUE THREAD

**Issue by d0ping** [odnoklassniki/ok-ios-sdk#15]
Доброго времени суток!
Авторизовался, получил токен. Пытаюсь получить список друзей через метод 
```objc
[OKSDK invokeMethod:@"friends.get" arguments:@{} success:... error:...];
```
но возвращает ошибку Error Domain=ru.ok.sdk Code=4 "unknown api response. Однако сам запрос выполняется корректно и ответ со списком друзей в ответе приходит.

**Comment by dgreenru** [comment]
Да там  @JsonValue на List, сейчас исправлю

**Comment by dgreenru** [comment]
пофиксил, версия 2.0.5

**Comment by d0ping** [comment]
Спасибо
