### ISSUE TITLE
Как я могу узнать что сессия не просрочена?

### ISSUE THREAD

**Issue by d0ping** [odnoklassniki/ok-ios-sdk#16]
В OKSDK есть методы авторизации и получения текущего токена, но нет информации о свежести сессии. Можно как то убедиться что сессия еще не просрочена и можно выполнять запросы к API?

**Comment by dgreenru** [comment]
Если вы используете LONG_ACCESS_TOKEN как написано в примере время жизни вашего  токена месяцы :)

**Comment by d0ping** [comment]
Так и есть LONG_ACCESS_TOKEN стоит в пермишенах, но сессия истекла после нескольких часов.

**Comment by dgreenru** [comment]
> Also your should send request for LONG_ACCESS_TOKEN to [api-support](mailto:api-support@ok.ru)

напишите в техподдержку  id вашего приложения с просьбой выдать эту пермиссию

**Comment by d0ping** [comment]
Написал. Расширение выдали. Спасибо
