### ISSUE TITLE
openUrl после рестарта приложения

### ISSUE THREAD

**Issue by AlexeyMeshkov** [odnoklassniki/ok-ios-sdk#20]
После переключения приложения на другое(приложение OK или браузер в данном случае) может привести к тому, что оно будет выгружено из памяти. После прохождения авторизации результат передаётся в приложение через URL. 

Проблема в том, что в случае с OK SDK это не сработает из-за того, что запрос на авторизацию регистрируется в completitionHandlers, а после перезапуска приложения это конечно же теряется. Таким образом если приложение потребляет сравнительно много памяти, то авторизация через ОК для него может просто не срабатывать.

**Comment by dgreenru** [comment]
Для урла равного  oauthRedirectUri можно сделать автоматический обработчик если он не найден.
Я смогу добратья до фикса этого кода скорее всего завтра. 

Eсли вы cможете сделать рабочий вариант и закинуть его в pull request я был бы благодарен.

**Comment by dgreenru** [comment]
готово, проверяйте currentAccessToken после запуска есть пользователь ещё не авторизован
