### ISSUE TITLE
openUrl return value

### ISSUE THREAD

**Issue by AlexeyMeshkov** [odnoklassniki/ok-ios-sdk#21]
Приложение, использующее OK SDK, может быть запущено с самым разными URL'ами. Было бы гораздо удобнее, если бы метод  openUrl возвращал BOOL. YES, если URL относится к OK и NO, в противном случае.

**Comment by dgreenru** [comment]
pull request? :)

**Comment by AlexeyMeshkov** [comment]
Нет, у меня пока нет решения... В сущности эту задачу надо делать вместе с [этой](https://github.com/odnoklassniki/ok-ios-sdk/issues/20).

**Comment by dgreenru** [comment]
ок. завтра планирую сделать

**Comment by dgreenru** [comment]
готово
